package controllerGrafica;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;

import client.InformazioniSessione;
import client.Observer;
import dominioPacchetto.Operazione;
import dominioPacchetto.Pacchetto;
import dominioPacchetto.TipoInfo;
import javafx.beans.InvalidationListener;
import javafx.collections.FXCollections;
import javafx.collections.ListChangeListener;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

public class GestioneGruppiController {
	@FXML
	private TextField nomeNuovoGruppo;
	@FXML
	private Button aggiungiNuovoGruppo;
	@FXML
	private ListView<String> elencoGruppi;
	@FXML
	private Button rimuoviUtente;
	@FXML
	private Button aggiungiUtente;
	@FXML
	private Button rimuoviGruppoSelezionato;
	@FXML
	private ListView<String> elencoUtenti;
	private Observer observer;
	private InformazioniSessione informazioniSessione;
	private ObservableList<String> tuttiUtenti;
	
	public GestioneGruppiController(Observer observer, InformazioniSessione informazioniSessione) {
		super();
		this.observer = observer;
		this.informazioniSessione = informazioniSessione;
		ObservableList<String> tuttiGruppi=FXCollections.observableArrayList();
		//per test inserisco solo i gruppi in cui è presente l'admin 
		tuttiGruppi.addAll(informazioniSessione.getGruppi());
		elencoGruppi.setItems(tuttiGruppi);
		tuttiUtenti=FXCollections.observableArrayList();
		//solo per test
		ArrayList<String> utenti=new ArrayList<String>();
		utenti.add("pippo");
		utenti.add("pluto");
		utenti.add("paperino");
		tuttiUtenti.setAll(utenti);
	}
	// Event Listener on Button[#aggiungiNuovoGruppo].onAction
	@FXML
	public void handlerAggiungiNuovoGruppo(ActionEvent event) {
		// TODO Autogenerated
		observer.trasmettiPacchetto(new Pacchetto(new Operazione(nomeNuovoGruppo.getText()),TipoInfo.CREA_GRUPPO));
	}
	// Event Listener on Button[#rimuoviUtente].onAction
	@FXML
	public void handlerRimuoviUtente(ActionEvent event) {
		// TODO Autogenerated
		observer.eliminaUtenteGruppo(elencoGruppi.getSelectionModel().getSelectedItem(), elencoUtenti.getSelectionModel().getSelectedItem());
	}
	// Event Listener on Button[#aggiungiUtente].onAction
	@FXML
	public void handlerAggiungiUtente(ActionEvent event) {
		// TODO Autogenerated
		//ricordarsi dal lato server di inviare a quel utente la notifica di aggiunta
		observer.aggiungiUtenteGruppo(elencoUtenti.getSelectionModel().getSelectedItem(), elencoGruppi.getSelectionModel().getSelectedItem());
	}
	// Event Listener on Button[#rimuoviGruppoSelezionato].onAction
	@FXML
	public void handlerRimuoviGruppoSelezionato(ActionEvent event) {
		// TODO Autogenerated
		observer.eliminaGruppo(elencoGruppi.getSelectionModel().getSelectedItem());
	}
}
