package dominioPacchetto;

import java.io.Serializable;

public enum TipoInfo implements Serializable {

	CONFERMA,
	RICHIESTA_CONTENUTI,
	CONTENUTI_GRUPPO,
	CONTENUTO,
	CREA_GRUPPO,
	ELIMINA_GRUPPO,
	AGG_UTENTE_GRUPPO,
	ELIMINA_UTENTE_GRUPPO,
	AGG_UTENTE,
	ELIMINA_UTENTE,
	VISUALIZZA_LOG,
	CAMBIA_PASSWORD,
	LISTA_UTENTI,
	LISTA_GRUPPI,
	LISTA_UTENTI_GRUPPO,
	LISTA_UTENTI_NON,
	ACCESSO,
	INFO_SESSIONE,
	DISCONNETTI;
	
}
