

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.time.LocalDateTime;
import java.util.ResourceBundle;

import dominioPacchetto.MessaggioTestuale;
import dominioPacchetto.Operazione;
import dominioPacchetto.Pacchetto;
import dominioPacchetto.TipoDestinatario;
import dominioPacchetto.TipoInfo;
import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

public class GruppoController implements Initializable{
	@FXML
	private TextArea corpoGruppo;
	@FXML
	private Button richiediContenuti;
	@FXML
	private TextArea textInvia;
	@FXML
	private Button invia;
	@FXML
	private Button selezionaFile;
	private InformazioniSessione informazioniSessione;
	private Observer observer;
	private String nomeGruppo;

	// Event Listener on Button[#richiediContenuti].onAction
	@FXML
	public void handlerRichiediContenuti(ActionEvent event) {
		// TODO Autogenerated
		observer.trasmettiPacchetto(new Pacchetto(new Operazione(this.nomeGruppo), TipoInfo.RICHIESTA_CONTENUTI));
	}
	// Event Listener on Button[#invia].onAction
	@FXML
	public void handlerInvia(ActionEvent event) {
		corpoGruppo.appendText(textInvia.getText());
		observer.inviaContenuto(new MessaggioTestuale(TipoDestinatario.GRUPPO,LocalDateTime.now(),informazioniSessione.getUsername(),nomeGruppo,textInvia.getText()));
	}
	
	public void aggiungiContenuto(String messaggio) {
		corpoGruppo.appendText(messaggio);
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
